### PR TITLE
feat: careless put

### PR DESCRIPTION
**Pull request by greged93**
Careless put mech instruction

### CODE REVIEW

**Comment by guiltygyoza** [comment]
@zinkkrysty would you be able to take a quick look at this PR? The changes look good to me but the build failed.

**Comment by zinkkrysty** [comment]
It seems to fail here:

```
2:07:57 PM: Failed to install Go version '1.19.x'
```

Not sure what Go has to do with any of these changes. Any way to rerun?

Changes look good to me

**Comment by guiltygyoza** [comment]
strangely the build now passes. I wonder why `Go` was ever involved.

**Review by guiltygyoza — APPROVED** [review]
I played with `c` a bit - it was fun hehe. Swift good work as always 👏

**Pull request merged**
