### PR TITLE
Christmas + DAW mode

### PR DESCRIPTION
**Pull request by guiltygyoza**
🎄 🎵 

Tasks
- [x] (@caseywescott) Formula effect mapped to music effect
- [x] (@caseywescott) Webapp loads default soundfont (Christmas bell)
- [x] (gg) Music Library panel accepts 0-delivery submissions
- [x] (gg) Load/Save support arena mode and daw mode; annotate name with mode
- [x] (@greged93 & gg) Contract+Backend+Frontend update to allow daw mode naming the submission
- [x] (@greged93 & gg) Contract+Backend+Frontend update to allow daw mode having different faucet&sink configuration than arena mode
- [x] (gg) Button in daw panel to reset all velocities to 60
- [x] (@caseywescott & gg) explain musical effects in Audio Workstation Manual
- [x] (gg) video walkthrough (https://dev.to/bravemaster619/simplest-way-to-embed-a-youtube-video-in-your-react-app-3bk2)

References
- festive color palettes: https://colorpalettes.net/color-palette-4121/

### CODE REVIEW

**Comment by zkpowergrind** [comment]
Fixed up the sound font player and has it triggering notes like a 10 string Guqin.  Given the option for loading custom soundfonts, I need to also add note off events for notes on previous steps.

**Comment by caseywescott** [comment]
Fixes the SoundFont player load issue and got the board to play notes of the 10 string Guqin. I need to add noteOff Functionality for notes of previous steps.

**Comment by guiltygyoza** [comment]
notes on video walkthroughs:

Part 1: Spirit Programming
https://www.youtube.com/watch?v=XFmgFOPUjbo

---
Part 2: Formulas Placement
https://www.youtube.com/watch?v=xnZupswvpCo

---
Part 3: First Complete Solution
https://www.youtube.com/watch?v=JtwYciqjcI0

**Review by caseywescott — APPROVED** [review]

**Comment by guiltygyoza** [comment]
This ends up being a really large commit, which should have been broken up to multiple PRs.

**Pull request merged**
